// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/get-app-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
var get_app_overview_default = defineTool({
  name: "get_app_overview",
  title: "Get app overview",
  description: "Describe AsteRISK Portal's capabilities, routes, and agent data boundaries.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{
      type: "text",
      text: JSON.stringify({
        name: "AsteRISK Portal",
        purpose: "Household inventory, expiry, shopping, medicine reminders, and waste reduction.",
        sections: ["Home", "Inventory", "Scan", "Shop", "Nudges", "Comm", "Feedback", "Settings"],
        dataBoundary: "Initial agent tools are read-only and expose app orientation plus authenticated household context, not inventory records.",
        contextUrl: "/ai-context.json"
      })
    }]
  })
});

// src/lib/mcp/tools/list-my-households.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function projectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is required");
  return url;
}
function publishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const values = Object.values(parsed);
        const key = values.find(
          (value) => typeof value === "string" && value.trim().startsWith("sb_publishable_")
        );
        if (key) return key.trim();
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("A publishable backend key is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("A verified OAuth token is required");
  return createClient(projectUrl(), publishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-my-households.ts
var list_my_households_default = defineTool2({
  name: "list_my_households",
  title: "List my households",
  description: "List the households available to the signed-in AsteRISK user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Sign in to view your households.");
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError("The signed-in user could not be identified.");
    const client = supabaseForUser(ctx);
    const { data: memberships, error: membershipError } = await client.from("household_members").select("household_id").eq("user_id", userId);
    if (membershipError) throw new ToolError(`Could not load household memberships: ${membershipError.message}`);
    const householdIds = (memberships ?? []).map((membership) => membership.household_id);
    if (householdIds.length === 0) {
      return { content: [{ type: "text", text: JSON.stringify({ households: [] }) }] };
    }
    const { data: households, error: householdError } = await client.from("households").select("id,name,invite_code,creator_id").in("id", householdIds);
    if (householdError) throw new ToolError(`Could not load households: ${householdError.message}`);
    return {
      content: [{ type: "text", text: JSON.stringify({ households: households ?? [] }) }]
    };
  }
});

// src/lib/mcp/tools/get-household-members.ts
import { defineTool as defineTool3, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";
var get_household_members_default = defineTool3({
  name: "get_household_members",
  title: "Get household members",
  description: "List the members of a household the signed-in user belongs to.",
  inputSchema: { household_id: z.string().describe("The household id returned by list_my_households.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ household_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Sign in to view household members.");
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError2("The signed-in user could not be identified.");
    const client = supabaseForUser(ctx);
    const { data: membership, error: membershipError } = await client.from("household_members").select("household_id").eq("household_id", household_id).eq("user_id", userId).maybeSingle();
    if (membershipError) throw new ToolError2(`Could not verify household access: ${membershipError.message}`);
    if (!membership) throw new ToolError2("You do not belong to that household.");
    const { data: members, error: membersError } = await client.from("household_members").select("user_id").eq("household_id", household_id);
    if (membersError) throw new ToolError2(`Could not load household members: ${membersError.message}`);
    const memberIds = (members ?? []).map((member) => member.user_id);
    if (memberIds.length === 0) {
      return { content: [{ type: "text", text: JSON.stringify({ household_id, members: [] }) }] };
    }
    const { data: profiles, error: profilesError } = await client.from("profiles").select("id,display_name").in("id", memberIds);
    if (profilesError) throw new ToolError2(`Could not load member profiles: ${profilesError.message}`);
    const profileById = new Map((profiles ?? []).map((profile) => [profile.id, profile.display_name]));
    const result = memberIds.map((memberId) => ({
      id: memberId,
      display_name: profileById.get(memberId) ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ household_id, members: result }) }]
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gvdmqynngjdhrugufamp";
var mcp_default = defineMcp({
  name: "remix-of-asterisk-portal",
  title: "Remix of AsteRISK - Portal",
  version: "0.1.0",
  instructions: "Read-only tools for understanding AsteRISK Portal and the signed-in user's household context.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_app_overview_default, list_my_households_default, get_household_members_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
